databases:
  - name: OSFF_DB
    databaseName: osff_db
    user: OSFF
    region: singapore

services:
  - type: web
    name: OSFF
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: OSFF_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

